title: minima
author: D Wiggins
email: wiggins.d4121@gmail.com
description.comn: > # this means to ignore newlines until "baseurl:"
  First test blog using jekyll on github

# social links
github_username:  dwiggins4121

show_excerpts: true # set to false to remove excerpts on the homepage
